/**
 * Providing a map storing old spus and new spus.
 */
export default class Spuses {
    static pairs = new Map([
        ['advancement test %entity %adv', 'execute if entity %0$addAdv%1'],
        ['advancement test %entity %adv %adv_crit', 'execute if entity %0$addAdv%1%2'],
        ['advancement %word %entity %word %adv', 'advancement %0 %1 %2 %3'],
        ['advancement %word %entity only %adv %adv_crit', 'advancement %0 %1 only %2 %3'],
        ['advancement %word %entity everything', 'advancement %0 %1 everything'],
        ['ban %entity', 'ban %0'],
        ['ban %entity %string..', 'ban %0 %1'],
        ['ban-ip %entity', 'ban-ip %0'],
        ['ban-ip %entity %string..', 'ban-ip %0 %1'],
        ['ban-ip %ip', 'ban-ip %0'],
        ['ban-ip %ip %string..', 'ban-ip %0 %1'],
        ['banlist %word', 'banlist %0'],
        ['blockdata %vec_3 %nbt', 'data merge block %0 %1'],
        ['clear', 'clear'],
        ['clear %entity', 'clear %0'],
        ['clear %entity %item', 'clear %0 %1'],
        ['clear %entity %item %data', 'clear %0 %1$addData%2'],
        ['clear %entity %item %data %num', 'clear %0 %1$addData%2 %3'],
        ['clear %entity %item %data %num %nbt', 'clear %0 %1$addData%2$addNbt%4'],
        ['clone %vec_3 %vec_3 %vec_3', 'clone %0 %1 %2'],
        ['clone %vec_3 %vec_3 %vec_3 %word', 'clone %0 %1 %2 %3'],
        ['clone %vec_3 %vec_3 %vec_3 %word %word', 'clone %0 %1 %2 %3 %4'],
        ['clone %vec_3 %vec_3 %vec_3 %word %word %block', 'clone %0 %1 %2 %3 %5 %4'],
        ['clone %vec_3 %vec_3 %vec_3 %word %word %block %data_or_state', 'clone %0 %1 %2 %3 %5$addDataOrState%6 %4'],
        ['debug %word', 'debug %0'],
        ['defaultgamemode %mode', 'defaultgamemode %0'],
        ['deop %entity', 'deop %0'],
        ['difficulty %difficulty', 'difficulty %0'],
        ['effect %entity clear', 'effect clear %0'],
        ['effect %entity %buff', 'effect give %0 %1'],
        ['effect %entity %buff %num', 'effect give %0 %1 %2'],
        ['effect %entity %buff %num %num', 'effect give %0 %1 %2 %3'],
        ['effect %entity %buff %num %num %bool', 'effect give %0 %1 %2 %3 %4'],
        ['enchant %entity %ench', 'enchant %0 %1'],
        ['enchant %entity %ench %num', 'enchant %0 %1 %2'],
        ['entitydata %entity %nbt', 'execute as %0 run data merge entity @s %1'],
        ['execute %entity %vec_3 %command', 'execute as %0 at @s positioned %1 run %2'],
        [
            'execute %entity %vec_3 detect %vec_3 %block %data_or_state %command',
            'execute as %0 at @s positioned %1 if block %2 %3$addDataOrState%4 run %5'
        ],
        ['fill %vec_3 %vec_3 %block', 'fill %0 %1 %2'],
        ['fill %vec_3 %vec_3 %block %data_or_state', 'fill %0 %1 %2$addDataOrState%3'],
        ['fill %vec_3 %vec_3 %block %data_or_state %word', 'fill %0 %1 %2$addDataOrState%3 %4'],
        ['fill %vec_3 %vec_3 %block %data_or_state %word %nbt', 'fill %0 %1 %2$addDataOrState%3$addNbt%5 %4'],
        [
            'fill %vec_3 %vec_3 %block %data_or_state replace %block %data_or_state',
            'fill %0 %1 %2$addDataOrState%3 replace %4$addDataOrState%5'
        ],
        ['function %func', 'function %0'],
        ['function %func %word %entity', 'execute %1 entity %2 run function %0'],
        ['gamemode %mode', 'gamemode %0'],
        ['gamemode %mode %entity', '%gamemode %0 %1'],
        ['gamerule %word', 'gamerule %0'],
        ['gamerule gameLoopFunction %word', "# Please add function '%0' into function tag '#minecraft:tick'."],
        ['gamerule %word %word', 'gamerule %0 %1'],
        ['give %entity %item', 'give %0 %1'],
        ['give %entity %item %num %data', 'give %0 %1$addData%3 %2'],
        ['give %entity %item %num %data %nbt', 'give %0 %1$addData%3$addNbt$4 %2'],
        ['help %word', 'help %0'],
        ['? %word', '? %0'],
        ['kick %entity', 'kick %0'],
        ['kick %entity %string..', 'kick %0 %1'],
        ['kill %entity', 'kill %0'],
        ['list', 'list'],
        ['list %uuid..', 'list %0'],
        [
            'locate Temple',
            '# locate <???>\n# ^Which temple do you want? Supports Desert_Pyramid, Igloo, Jungle_Pyramid and Swamp_hut.'
        ],
        ['locate %word', 'locate %0'],
        ['me %string..', 'me %0'],
        ['op %entity', 'op %0'],
        ['pardon %word', '%pardon %0'],
        ['pardon-ip %ip', 'pardon-ip %0'],
        ['particle %particle %vec_3 %vec_3 %num', 'particle %0 %1 %2 %3'],
        ['particle %particle %vec_3 %vec_3 %num %num', 'particle %0 %1 %2 %3 %4'],
        ['particle %particle %vec_3 %vec_3 %num %num %word', 'particle %0 %1 %2 %3 %4 %5'],
        ['particle %particle %vec_3 %vec_3 %num %num %word %entity', 'particle %0 %1 %2 %3 %4 %5 %6'],
        // TODO: ['particle %particle %vec_3 %vec_3 %num %num %word %entity %dust', '# FUCK YOU, NUMERIC IDS!'],
        ['playsound %sound %source %entity', 'playsound %0 %1 %2'],
        ['playsound %sound %source %entity %vec_3', 'playsound %0 %1 %2 %3'],
        ['playsound %sound %source %entity %vec_3 %num', 'playsound %0 %1 %2 %3 %4'],
        ['playsound %sound %source %entity %vec_3 %num %num', 'playsound %0 %1 %2 %3 %4 %5'],
        ['playsound %sound %source %entity %vec_3 %num %num %num', 'playsound %0 %1 %2 %3 %4 %5 %6'],
        ['publish', 'publish'],
        // TODO: %recipe should contain * and resource location.
        ['recipe %word %recipe', 'recipe %0 %1'],
        ['recipe %word %entity %recipe', 'recipe %0 %1 %2'],
        ['reload', 'reload'],
        ['replaceitem block %vec_3 %slot %item', 'replaceitem block %0 %1 %2'],
        ['replaceitem block %vec_3 %slot %item %num', 'replaceitem block %0 %1 %2 %3'],
        ['replaceitem block %vec_3 %slot %item %num %data', 'replaceitem block %0 %1 %2$addData%4 %3'],
        ['replaceitem block %vec_3 %slot %item %num %data %nbt', 'replaceitem block %0 %1 %2$addData%4$addNbt%5 %3'],
        ['replaceitem entity %entity %slot %item', 'replaceitem block %0 %1 %2'],
        ['replaceitem entity %entity %slot %item %num', 'replaceitem block %0 %1 %2 %3'],
        ['replaceitem entity %entity %slot %item %num %data', 'replaceitem block %0 %1 %2$addData%4 %3'],
        ['replaceitem entity %entity %slot %item %num %data %nbt', 'replaceitem block %0 %1 %2$addData%4$addNbt%5 %3'],
        ['save-all', 'save-all'],
        ['save-all %word', 'save-all %0'],
        ['save-off', 'save-off'],
        ['save-on', 'save-on'],
        ['say %string..', 'say %0'],
        ['scoreboard objectives list', 'scoreboard objectives list'],
        ['scoreboard objectives add %word %scb_crit', 'scoreboard objectives add %0 %1'],
        ['scoreboard objectives add %word %scb_crit %string', 'scoreboard objectives add %0 %1 %2'],
        ['scoreboard objectives remove %word', 'scoreboard objectives remove %0'],
        ['scoreboard objectives setdisplay %word', 'scoreboard objectives setdisplay %0'],
        ['scoreboard objectives setdisplay %word %word', 'scoreboard objectives setdisplay %0 %1'],
        // TODO: scoreboards
        ['seed', 'seed'],
        ['setblock %vec_3 %block', 'setblock %0 %1'],
        ['setblock %vec_3 %block %data_or_state', 'setblock %0 %1%addDataOrState%2'],
        ['setblock %vec_3 %block %data_or_state %word', 'setblock %0 %1%addDataOrState%2 %3'],
        ['setblock %vec_3 %block %data_or_state %word %nbt', 'setblock %0 %1%addDataOrState%2$addNbt%4 %3'],
        ['setidletimeout %num', 'setidletimeout %0'],
        ['setworldspawn', 'setworldspawn'],
        ['setworldspawn %vec_3', 'setworldspawn %0'],
        ['spawnpoint', 'spawnpoint'],
        ['spawnpoint %entity', 'spawnpoint %0'],
        ['spawnpoint %entity %vec_3', 'spawnpoint %0 %1'],
        ['spreadplayers %vec_2 %num %num %bool %entity..', 'spreadplayers %0 %1 %2 %3 %4'],
        ['stats %string..', "# Couldn't convert 'stat' commands. Use 'execute store ...'!"],
        ['stop', 'stop'],
        ['stopsound %entity', 'stopsound %0'],
        ['stopsound %entity %word', 'stopsound %0 %1'],
        ['stopsound %entity %word %sound', 'stopsound %0 %1 %2'],
        ['summon %entity_type', 'summon %0'],
        ['summon %entity_type %vec_3', 'summon %0 %1'],
        ['summon %entity_type %vec_3 %nbt', 'summon %0 %1 %2'],
        ['teleport %entity %vec_3', 'teleport %0 %1'],
        ['teleport %entity %vec_3 %vec_2', 'teleport %0 %1 %2'],
        ['tell %entity %string..', 'tell %0 %1'],
        ['msg %entity %string..', 'msg %0 %1'],
        ['w %entity %string..', 'w %0 %1'],
        ['tellraw %entity %string..', 'tellraw %0 %1'],
        ['testfor %entity', 'execute if entity %0'],
        ['testfor %entity %nbt', 'execute if entity %0$addNbt%1'],
        // TODO: testforblock
        ['', ''],
        ['', ''],
        ['', ''],
        ['', ''],
        ['', ''],
        ['', ''],
        ['', ''],
        ['', ''],
        ['', ''],
        ['', ''],
        ['', '']
    ])
}
