import { CmdNode } from '../utils/wheel_chief/wheel_chief';
/**
 * Generated by data generator
 * @version Minecraft: Java Editon 1.13.1
 */
export declare class Commands113To114 {
    static commands: CmdNode;
}
